%%
%% Autogenerated by Thrift Compiler (0.12.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(premium_manager_thrift).
-behaviour(thrift_service).


-include("premium_manager_thrift.hrl").

-export([struct_info/1, function_info/2, function_names/0]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% takeLoan(This, LoanRequest)
function_info('takeLoan', params_type) ->
  {struct, [{1, {struct, {'bank_schema_types', 'LoanRequest'}}}]}
;
function_info('takeLoan', reply_type) ->
  {struct, {'bank_schema_types', 'LoanResponse'}};
function_info('takeLoan', exceptions) ->
  {struct, [{1, {struct, {'bank_schema_types', 'ErrorInOperation'}}}]}
;
function_info(Function, InfoType) ->
  standard_manager_thrift:function_info(Function, InfoType).

function_names() -> 
  ['takeLoan'].

