%%
%% Autogenerated by Thrift Compiler (0.12.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(register_client_thrift).
-behaviour(thrift_service).


-include("register_client_thrift.hrl").

-export([struct_info/1, function_info/2, function_names/0]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% registerClient(This, Person, InitInput)
function_info('registerClient', params_type) ->
  {struct, [{1, {struct, {'bank_schema_types', 'PersonalData'}}},
          {2, {struct, {'bank_schema_types', 'Money'}}}]}
;
function_info('registerClient', reply_type) ->
  {struct, {'bank_schema_types', 'RegisterUserReponse'}};
function_info('registerClient', exceptions) ->
  {struct, [{1, {struct, {'bank_schema_types', 'ErrorInOperation'}}}]}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

function_names() -> 
  ['registerClient'].

