%%
%% Autogenerated by Thrift Compiler (0.12.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(standard_manager_thrift).
-behaviour(thrift_service).


-include("standard_manager_thrift.hrl").

-export([struct_info/1, function_info/2, function_names/0]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% getBalance(This, Login)
function_info('getBalance', params_type) ->
  {struct, [{1, {struct, {'bank_schema_types', 'Login'}}}]}
;
function_info('getBalance', reply_type) ->
  {struct, {'bank_schema_types', 'Money'}};
function_info('getBalance', exceptions) ->
  {struct, [{1, {struct, {'bank_schema_types', 'ErrorInOperation'}}}]}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

function_names() -> 
  ['getBalance'].

